### Prueba de Login para obtener Tokens
POST http://localhost:8000/api/v1/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "Password"
}

### Prueba de endpoint protegido (Debería dar 403 o 401 por ahora)
GET http://localhost:8000/api/v1/products