# Cambio de puerto para evitar conflictos con el módulo web
server.port=8000

# Nombre específico para este módulo
spring.application.name=tienda-jd-api

# Configuración de la conexión a H2 (Igual que en web)
spring.datasource.url=jdbc:h2:mem:shop;DATABASE_TO_LOWER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Configuración del comportamiento de Hibernate (Igual que en web)
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Habilitar consola web de H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Asegura que la base de datos se inicialice después de que Hibernate cree las tablas
spring.jpa.defer-datasource-initialization=true

# Configuración JWT
# Esta es una clave de ejemplo en Base64 (debe ser secreta y larga)
jwt.secret=9ikZyrfbMyzcPFaK72vrJ4TVwQ6maL58PscRCg44RjtVi7V7zayfrni4PNLECbZZ
# Tiempos en milisegundos (ej: 15 min acceso, 24h refresco)
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=86400000